---
abstract: 'An example XS wrap_op_check implementation '
author:
  - 'Matthew Horsfall <WolfSage@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.86, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Wrap-Op-Checker
no_index:
  directory:
    - t
    - inc
requires: {}
version: 0.01
