---
abstract: 'Example class in XS for hiding C data from Perl'
author:
  - 'Matthew Horsfall <WolfSage@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.8, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Simple-Class-Private-Data-Any
no_index:
  directory:
    - t
    - inc
requires: {}
version: 0.01
